services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27070:27017
    volumes:
      - .mongodb:/data/db
    restart: always
  ai-chat:
    image: ai-chat
    container_name: ai-chat
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  deepseek:
    container_name: ollama-deepseek
    image: ollama/ollama:latest
    volumes:
      - .ollama:/root/.ollama
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh
    ports:
      - 11434:11434
    pull_policy: always
    tty: true
    restart: always
    entrypoint: ["/usr/bin/bash", "/ollama-entrypoint.sh"]

volumes:
  .mongodb:
  .ollama:
